import unittest
from collections import namedtuple
from betty.api import OpenAI
from parameterized import parameterized

# Mock the Message type if it's not directly accessible
Message = namedtuple("Message", "role content")


class TestOpenAI(unittest.IsolatedAsyncioTestCase):
    @parameterized.expand(
        [
            (
                [
                    {"content": ""},
                    {"content": "Here"},
                    {"content": "'s"},
                    {"content": " an"},
                    {"content": " example"},
                    {"content": " JSON"},
                    {"content": " array"},
                    {"content": " of"},
                    {"content": " JSON"},
                    {"content": " objects"},
                    {"content": ":\n\n"},
                    {"content": "``"},
                    {"content": "`\n"},
                    {"content": "[\n"},
                    {"content": " "},
                    {"content": " {\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "name"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "John"},
                    {"content": '",\n'},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "age"},
                    {"content": '":'},
                    {"content": " "},
                    {"content": "25"},
                    {"content": ",\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "gender"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "male"},
                    {"content": '",\n'},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "address"},
                    {"content": '":'},
                    {"content": " {\n"},
                    {"content": "     "},
                    {"content": ' "'},
                    {"content": "street"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "123"},
                    {"content": " Main"},
                    {"content": " St"},
                    {"content": '",\n'},
                    {"content": "     "},
                    {"content": ' "'},
                    {"content": "city"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "Any"},
                    {"content": "town"},
                    {"content": '",\n'},
                    {"content": "     "},
                    {"content": ' "'},
                    {"content": "state"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "CA"},
                    {"content": '"\n'},
                    {"content": "   "},
                    {"content": " }\n"},
                    {"content": " "},
                    {"content": " },\n"},
                    {"content": " "},
                    {"content": " {\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "name"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "Jane"},
                    {"content": '",\n'},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "age"},
                    {"content": '":'},
                    {"content": " "},
                    {"content": "30"},
                    {"content": ",\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "gender"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "female"},
                    {"content": '",\n'},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "address"},
                    {"content": '":'},
                    {"content": " {\n"},
                    {"content": "     "},
                    {"content": ' "'},
                    {"content": "street"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "456"},
                    {"content": " Elm"},
                    {"content": " St"},
                    {"content": '",\n'},
                    {"content": "     "},
                    {"content": ' "'},
                    {"content": "city"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "O"},
                    {"content": "th"},
                    {"content": "ert"},
                    {"content": "own"},
                    {"content": '",\n'},
                    {"content": "     "},
                    {"content": ' "'},
                    {"content": "state"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "NY"},
                    {"content": '"\n'},
                    {"content": "   "},
                    {"content": " }\n"},
                    {"content": " "},
                    {"content": " },\n"},
                    {"content": " "},
                    {"content": " {\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "name"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "Bob"},
                    {"content": '",\n'},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "age"},
                    {"content": '":'},
                    {"content": " "},
                    {"content": "40"},
                    {"content": ",\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "gender"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "male"},
                    {"content": '",\n'},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "address"},
                    {"content": '":'},
                    {"content": " {\n"},
                    {"content": "     "},
                    {"content": ' "'},
                    {"content": "street"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "789"},
                    {"content": " Oak"},
                    {"content": " St"},
                    {"content": '",\n'},
                    {"content": "     "},
                    {"content": ' "'},
                    {"content": "city"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "Som"},
                    {"content": "ewhere"},
                    {"content": '",\n'},
                    {"content": "     "},
                    {"content": ' "'},
                    {"content": "state"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "TX"},
                    {"content": '"\n'},
                    {"content": "   "},
                    {"content": " }\n"},
                    {"content": " "},
                    {"content": " }\n"},
                    {"content": "]\n"},
                    {"content": "``"},
                    {"content": "`\n\n"},
                    {"content": "This"},
                    {"content": " JSON"},
                    {"content": " array"},
                    {"content": " contains"},
                    {"content": " three"},
                    {"content": " JSON"},
                    {"content": " objects"},
                    {"content": " that"},
                    {"content": " all"},
                    {"content": " have"},
                    {"content": " the"},
                    {"content": " same"},
                    {"content": " properties"},
                    {"content": ":"},
                    {"content": " `"},
                    {"content": "name"},
                    {"content": "`,"},
                    {"content": " `"},
                    {"content": "age"},
                    {"content": "`,"},
                    {"content": " `"},
                    {"content": "gender"},
                    {"content": "`,"},
                    {"content": " and"},
                    {"content": " `"},
                    {"content": "address"},
                    {"content": "`."},
                    {"content": " Each"},
                    {"content": " address"},
                    {"content": " property"},
                    {"content": " is"},
                    {"content": " itself"},
                    {"content": " another"},
                    {"content": " JSON"},
                    {"content": " object"},
                    {"content": " that"},
                    {"content": " contains"},
                    {"content": " `"},
                    {"content": "street"},
                    {"content": "`,"},
                    {"content": " `"},
                    {"content": "city"},
                    {"content": "`,"},
                    {"content": " and"},
                    {"content": " `"},
                    {"content": "state"},
                    {"content": "`"},
                    {"content": " properties"},
                    {"content": ".\n\n"},
                    {"content": "This"},
                    {"content": " example"},
                    {"content": " JSON"},
                    {"content": " array"},
                    {"content": " could"},
                    {"content": " be"},
                    {"content": " used"},
                    {"content": " to"},
                    {"content": " represent"},
                    {"content": " a"},
                    {"content": " list"},
                    {"content": " of"},
                    {"content": " people"},
                    {"content": "'s"},
                    {"content": " information"},
                    {"content": ","},
                    {"content": " where"},
                    {"content": " each"},
                    {"content": " object"},
                    {"content": " represents"},
                    {"content": " one"},
                    {"content": " person"},
                    {"content": "'s"},
                    {"content": " data"},
                    {"content": "."},
                    {"content": " It"},
                    {"content": " could"},
                    {"content": " be"},
                    {"content": " used"},
                    {"content": " in"},
                    {"content": " a"},
                    {"content": " database"},
                    {"content": " or"},
                    {"content": " API"},
                    {"content": " response"},
                    {"content": " to"},
                    {"content": " store"},
                    {"content": " and"},
                    {"content": " retrieve"},
                    {"content": " this"},
                    {"content": " data"},
                    {"content": "."},
                    {"content": ""},
                ],
            ),
            (
                [
                    {"content": ""},
                    {"content": "[\n"},
                    {"content": " "},
                    {"content": " {\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "id"},
                    {"content": '":'},
                    {"content": " "},
                    {"content": "1"},
                    {"content": ",\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "name"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "John"},
                    {"content": '",\n'},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "age"},
                    {"content": '":'},
                    {"content": " "},
                    {"content": "30"},
                    {"content": "\n"},
                    {"content": " "},
                    {"content": " },\n"},
                    {"content": " "},
                    {"content": " {\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "id"},
                    {"content": '":'},
                    {"content": " "},
                    {"content": "2"},
                    {"content": ",\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "name"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "Jane"},
                    {"content": '",\n'},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "age"},
                    {"content": '":'},
                    {"content": " "},
                    {"content": "25"},
                    {"content": "\n"},
                    {"content": " "},
                    {"content": " },\n"},
                    {"content": " "},
                    {"content": " {\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "id"},
                    {"content": '":'},
                    {"content": " "},
                    {"content": "3"},
                    {"content": ",\n"},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "name"},
                    {"content": '":'},
                    {"content": ' "'},
                    {"content": "Bob"},
                    {"content": '",\n'},
                    {"content": "   "},
                    {"content": ' "'},
                    {"content": "age"},
                    {"content": '":'},
                    {"content": " "},
                    {"content": "35"},
                    {"content": "\n"},
                    {"content": " "},
                    {"content": " }\n"},
                    {"content": "]"},
                    {"content": ""},
                ],
            ),
        ]
    )
    async def test_stream_json(self, return_messages):
        # Create an instance of your class
        api = OpenAI(api_key="mock-api-key")

        messages = [
            Message(
                role="user", content="Yields JSON objects from a streaming response."
            )
        ]

        # Define an async generator function to simulate the streaming response
        async def mock_stream_completion(*args, **kwargs):
            for msg in return_messages:
                yield msg

        # Mock the stream_completion method to return the messages
        api.stream_completion = mock_stream_completion

        # Call the method and collect the results
        results = []
        async for result in api.stream_json(messages):
            results.append(result)

        # keys = ["id", "name", "age", "email"]
        # Check the results
        self.assertTrue(isinstance(results, list))
        self.assertTrue(all(isinstance(results[i], dict) for i in range(len(results))))
        # self.assertTrue(
        #     all(key in results[i] for i in range(len(results)) for key in keys)
        # )


if __name__ == "__main__":
    unittest.main()
